---
creation_rules:
  - # IMPORTANT: Keep this rule first
    path_regex: talos/.+\.secret(\.sops)?\.ya?ml
    input_type: yaml
    encrypted_regex: ^(token|crt|key|id|secret|secretboxEncryptionSecret|ca)$
    key_groups:
      - age:
          - "age1zucujcrr89pecplrme76f4vxcc05lg3hm8849mmfggvcvcv4ppls7cquw8"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1zucujcrr89pecplrme76f4vxcc05lg3hm8849mmfggvcvcv4ppls7cquw8"
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1zucujcrr89pecplrme76f4vxcc05lg3hm8849mmfggvcvcv4ppls7cquw8"
