---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: luke@mullan.net.au
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            email: luke@mullan.net.au
            apiKeySecretRef:
              name: cloudflare-secret
              key: CLOUDFLARE_API_KEY
        selector:
          dnsZones:
            - lumu.au
            - mullan.net.au
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: luke@mullan.net.au
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            email: luke@mullan.net.au
            apiKeySecretRef:
              name: cloudflare-secret
              key: CLOUDFLARE_API_KEY
        selector:
          dnsZones:
            - lumu.au
            - mullan.net.au
