---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: plex
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: plex-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        PLEX_TOKEN: "{{ .token }}"
  dataFrom:
    - extract:
        key: plex-token