---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app invidious-server
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      invidious:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
              pullPolicy: IfNotPresent
            envFrom: &envFrom
              - secretRef:
                  name: &secret invidious-secret
        containers:
          app:
            image:
              repository: quay.io/invidious/invidious
              tag: 2024.03.31-08390ac@sha256:b46c32a88d7038b18226e62e59349c50541c1c80345111bf1cf8033861e8780d
              pullPolicy: IfNotPresent
            envFrom: *envFrom
    service:
      app:
        controller: invidious
        ports:
          http:
            port: 3000
    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: ingress.lumu.au
        hosts:
          - host: &host "invidious.lumu.au"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    # persistence:
    #   config:
    #     enabled: false
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
